# Production server configuration (Ubuntu VPS)

server {
    listen 80;
    server_name www.cyphro.io;

    # Redirect from www to non-www
    return 301 http://cyphro.io$request_uri;
}

server {
    listen 80;
    server_name cyphro.io;

    # Path to deployed static files on VPS
    root /var/www/html;

    # Log files (managed by logrotate)
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    include /etc/nginx/common/app.conf;
}